[build]
    command = "tsc && vite build"
    publish = "dist"

[dev]
    command = "vite"
    port = 3000

[[headers]]
  for = "/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"